name: Test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  check:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        uses: pnpm/action-setup@v2.2.3
        with:
          version: 7

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'

      - name: Prepare
        run: pnpm install

      - name: Prepare
        run: pnpm typecheck
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        uses: pnpm/action-setup@v2.2.3
        with:
          version: 7

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'

      - name: Build
        run: |
          pnpm install
          pnpm run --if-present build

      - name: Test
        run: pnpm run test